image: Visual Studio 2017

environment:
  ninja: https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip
  repo: https://github.com/llvm-mirror/llvm
  branch: release_60
  targets: AArch64;ARM;X86
  matrix:
    # AMD64, Shared, Dynamic CRT
    - arch: amd64
      shared: ON
      crt: MD
    # AMD64, Static, Dynamic CRT
    - arch: amd64
      shared: OFF
      crt: MD
    # AMD64, Static, Static CRT
    - arch: amd64
      shared: OFF
      crt: MT

artifacts:
  - path: llvm-*.zip
    name: LLVM

install:
  # Install Ninja
  - appveyor DownloadFile %ninja% -FileName ninja.zip
  - 7z x ninja.zip -oC:\ninja > nul
  - set PATH=C:\ninja;%PATH%
  - ninja --version
  # Download LLVM sources
  - git clone -q --depth=1 --branch %branch% %repo% llvm-src

build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\vsdevcmd.bat" -arch=%arch% -host_arch=amd64 -no_logo
  - cd %APPVEYOR_BUILD_FOLDER%
  - if "%shared%" == "ON" (set linktype=shared) else set linktype=static
  - set prefix=llvm-%branch%-win-%arch%-Release-%linktype%-%crt%
  - mkdir %prefix%
  - mkdir build && cd build
  # Only the "ps" script type supports multiple lines, but PowerShell treats
  # writes to stderr as actual errors that will fail the build. Redirecting
  # stderr to stdout isn't enough. We also have to run the command inside a
  # cmd.exe sub-process. Ugh.
  - ps: |
      cmd /c "cmake 2>&1" -G Ninja `
        "-DCMAKE_INSTALL_PREFIX:STRING=$env:APPVEYOR_BUILD_FOLDER\$env:prefix" `
        "-DCMAKE_BUILD_TYPE:STRING=Release" `
        "-DLLVM_TARGETS_TO_BUILD:STRING=$env:targets" `
        -DLLVM_INCLUDE_TOOLS:BOOL=NO `
        -DLLVM_INCLUDE_UTILS:BOOL=NO `
        -DLLVM_INCLUDE_RUNTIMES:BOOL=NO `
        -DLLVM_INCLUDE_DOCS:BOOL=NO `
        -DLLVM_INCLUDE_EXAMPLES:BOOL=NO `
        -DLLVM_INCLUDE_TESTS:BOOL=NO `
        -DLLVM_ENABLE_EH:BOOL=NO `
        -DLLVM_ENABLE_RTTI:BOOL=NO `
        -DLLVM_ENABLE_FFI:BOOL=NO `
        -DLLVM_ENABLE_ZLIB:BOOL=NO `
        -DLLVM_BUILD_LLVM_DYLIB:BOOL=$env:shared `
        -DLLVM_USE_CRT_RELEASE:BOOL=$env:crt `
        -DLLVM_OPTIMIZED_TABLEGEN:BOOL=YES `
        ..\llvm-src
  - cmake --build . --target install
  - cd ..
  - 7z a %prefix%.zip %prefix% > nul
