image: Visual Studio 2017

environment:
  branch: release_60
  targets: all
  matrix:
    - arch: AMD64
      config: Debug

install:
  - ps: |
      Push-Location
      Set-Location C:\
      git clone -q --depth=1 --branch $env:branch https://github.com/llvm-mirror/llvm src
      Pop-Location

build_script:
  - ps: |
      .\Build-LLVM.ps1 -Architecture $env:arch -Configuration $env:config `
        -SourceDirectory "C:\src" -BuildDirectory "C:\build" `
        -InstallDirectory "C:\install" -Targets $env:targets
